version: '3'

services:

  fake-quotes-svc--version:
    image: docker.io/goforbroke1006/fake-quotes-svc:latest
    command: [ "version" ]

  fake-quotes-svc--emit-websocket:
    image: docker.io/goforbroke1006/fake-quotes-svc:latest
    command: [ "emit", "websocket" ]
    volumes:
      - "./config.yaml:/app/config.yaml"
    ports:
      - 18081:8080

  fake-quotes-svc--emit-websocket--debug:
    image: nginx:1.17
    volumes:
      - "./emit-websocket-debug.html:/usr/share/nginx/html/index.html"
    ports:
      - 18082:80
    links:
      - fake-quotes-svc--emit-websocket
